# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-19 15:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=30)),
                ('expiry_date', models.DateTimeField(verbose_name='expiry date')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=3)),
                ('comment', models.CharField(max_length=200)),
                ('written_date', models.DateTimeField(auto_now_add=True)),
                ('course_code', models.CharField(max_length=10)),
                ('state', models.CharField(default='empty', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('available_timeslot', models.CharField(default='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_used', models.BooleanField()),
                ('session_datetime', models.DateTimeField()),
                ('state', models.CharField(default='normal', max_length=10)),
                ('review_state', models.CharField(default='empty', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=10)),
                ('photo_url', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=10)),
                ('photo_url', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('tutor_type', models.CharField(default='Private', max_length=8)),
                ('university', models.CharField(max_length=60)),
                ('subject_tag', models.CharField(max_length=60)),
                ('hourly_rate', models.IntegerField(default=100)),
                ('introduction', models.TextField(default='I love programming')),
                ('activated', models.BooleanField(default=True)),
                ('avg_review', models.IntegerField(default=-1)),
                ('teach_course_code', models.ManyToManyField(to='mainApp.SubjectCode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Student')),
                ('tutor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Tutor')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='belong_wallet',
            field=models.ManyToManyField(to='mainApp.Wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='involved_session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Session'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Student'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Tutor'),
        ),
        migrations.AddField(
            model_name='session',
            name='session_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Student'),
        ),
        migrations.AddField(
            model_name='session',
            name='session_tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Tutor'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='owned_tutor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Tutor'),
        ),
        migrations.AddField(
            model_name='review',
            name='for_tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Tutor'),
        ),
        migrations.AddField(
            model_name='review',
            name='involved_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Session'),
        ),
        migrations.AddField(
            model_name='review',
            name='written_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Student'),
        ),
    ]
