# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='teach_course_code',
        ),
        migrations.AddField(
            model_name='tutor',
            name='teach_course_code',
            field=models.ManyToManyField(to='mainApp.SubjectCode'),
        ),
    ]
