# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20171023_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='owned_wallet',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='in_wallet',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='owned_wallet',
        ),
        migrations.AddField(
            model_name='student',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='available_timeslot',
            field=models.CharField(max_length=280),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
