# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20171024_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='tutor_type',
            field=models.CharField(max_length=8),
        ),
    ]
